apiVersion: platform.nttdata.io/v1alpha1
kind: AppModelA
metadata:
  name: webapp-l1h8
  namespace: kratix-worker-system
  labels:
    app: webapp-l1h8
    created-by: backstage
    request-id: "l1h8"
  annotations:
    backstage.io/created-at: ""
    backstage.io/requested-by: "unknown"
spec:
  appName: webapp-l1h8
  namespace: default-l1h8
  image: nginx:latest
  port: 79
  replicas: 1
  serviceType: ClusterIP
  imagePullPolicy: Always
  gateway:
    enabled: true
    hostname: "myapp.nttdataco.com"
    gatewayName: "nginx-gateway"
    gatewayNamespace: "nginx-gateway-system"
    path: "/"
    tls: false
  storage:
    enabled: true
    size: "1Gi"
    storageClass: "gp2"
    mountPath: "/data"
  database:
    enabled: true
    type: "postgresql"
    claimName: "webapp-l1h8-db"
    parameters:
      engine: "postgres"
      version: "15"
      instanceSize: "small"
      storageGB: 10
      username: "{{ values.appName }}user"
      publiclyAccessible: false