apiVersion: platform.nttdata.io/v1alpha1
kind: AppModelA
metadata:
  name: webapp-0xcl
  namespace: kratix-worker-system
  labels:
    app: webapp-0xcl
    created-by: backstage
    request-id: "0xcl"
  annotations:
    backstage.io/created-at: ""
    backstage.io/requested-by: "unknown"
spec:
  appName: webapp-0xcl
  namespace: default-0xcl
  image: nginx:latest
  port: 80
  replicas: 1
  serviceType: ClusterIP
  imagePullPolicy: Always
  gateway:
    enabled: true
    hostname: "myapp.nttdataco.com"
    gatewayName: "nginx-gateway"
    gatewayNamespace: "nginx-gateway-system"
    path: "/"
    tls: false
  storage:
    enabled: true
    size: "1Gi"
    storageClass: "gp3"
    mountPath: "/data"
  database:
    enabled: true
    type: "postgresql"
    claimApiVersion: "database.example.org/v1alpha1"
    claimKind: "PostgreSQLInstance"
    claimName: "webapp-0xcl-db"
    parameters:
      engine: "postgres"
      version: "15"
      instanceSize: "small"
      storageGB: 10
      username: "{{ values.appName }}user"
      publiclyAccessible: false